// Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');
  FfiGenerator(
    headers: Headers(
      entryPoints: [
        packageRoot.resolve('third_party/wasmtime/include/wasmtime.h'),
      ],
      compilerOptions: ['-Ithird_party/wasmtime/include'],
    ),
    functions: Functions.includeSet({
      'wasm_engine_new',
      'wasm_engine_delete',
      'wasm_config_new',
      'wasm_config_delete',
      'wasm_engine_new_with_config',
      'wasmtime_engine_increment_epoch',
      'wasmtime_engine_is_pulley',
      'wasmtime_store_new',
      'wasmtime_store_delete',
      'wasmtime_store_context',
      'wasmtime_context_gc',
      'wasmtime_context_get_data',
      'wasmtime_module_new',
      'wasmtime_module_delete',
      'wasmtime_module_validate',
      'wasmtime_wat2wasm',
      'wasm_byte_vec_new',
      'wasm_byte_vec_delete',
      'wasmtime_linker_new',
      'wasmtime_linker_delete',
      'wasmtime_linker_allow_shadowing',
      'wasmtime_linker_define',
      'wasmtime_linker_define_func',
      'wasmtime_linker_define_wasi',
      'wasmtime_linker_define_instance',
      'wasmtime_linker_instantiate',
      'wasmtime_linker_module',
      'wasmtime_linker_get_default',
      'wasmtime_linker_get',
      'wasmtime_func_new',
      'wasmtime_func_call',
      'wasmtime_func_type',
      'wasm_functype_new',
      'wasm_functype_delete',
      'wasm_functype_params',
      'wasm_functype_results',
      'wasm_valtype_new',
      'wasm_valtype_kind',
      'wasmtime_caller_context',
      'wasmtime_caller_export_get',
      'wasm_trap_new',
      'wasm_trap_message',
      'wasm_trap_delete',
      'wasm_trap_trace',
      'wasm_frame_vec_delete',
      'wasmtime_trap_code',
      'wasmtime_trap_exit_status',
      'wasmtime_instance_export_get',
      'wasmtime_extern_delete',
      'wasm_valtype_delete',
      'wasmtime_externref_new',
      'wasmtime_externref_data',
      'wasmtime_externref_from_raw',
      'wasmtime_externref_to_raw',
      'wasm_frame_func_index',
      'wasm_frame_func_offset',
      'wasm_frame_module_offset',
      'wasmtime_frame_func_name',
      'wasmtime_frame_module_name',
    }),
    output: Output(
      dartFile: packageRoot.resolve('lib/src/third_party/wasmtime.g.dart'),
    ),
    structs: Structs.includeSet({
      'wasm_byte_vec_t',
      'wasmtime_linker_t',
      'wasmtime_func_t',
      'wasmtime_func',
      'wasmtime_caller_t',
      'wasm_trap_t',
      'wasm_val_t',
      'wasm_val',
      'wasm_functype_t',
      'wasm_valtype_t',
      'wasmtime_extern_t',
      'wasmtime_extern',
      'wasmtime_instance_t',
      'wasmtime_instance',
      'wasm_frame_vec_t',
    }),
  ).generate();
}
